### ISSUE TITLE
Any plans to support vitest 2+ ?

### ISSUE THREAD

**Issue by cainus** [mcous/testdouble-vitest#6]
Any plans to support vitest 2+ ?

```
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@">=0.25.0 <2.0.0" from testdouble-vitest@0.1.3
npm ERR! node_modules/testdouble-vitest
npm ERR!   testdouble-vitest@"*" from the root project
```

**Comment by mcous** [comment]
Hi @cainus, I haven’t looked into it yet! I love testdouble, but I’ve found that [vitest-when](https://github.com/mcous/vitest-when) gets me most of what I need while using Vitest module replacement and mocks directly. It tends to run faster in my suites than trying to integrate with testdouble, since that’s what Vitest itself is optimizing for.

I’ll take a look into the version bump, and if it’s a simple peer dep update, it won’t be much trouble to issue an update
